### ISSUE TITLE
error like this. 

### ISSUE THREAD

**Issue by gaopeng91** [Navhkrin/DepthVisualizer#1]
Hi, thanks for your code, when using renderer = DepthRenderer(1200, 800, camera_fov=100), show this error. can you tell me how to solve it?
/home/users/peng.gao/env/py3.6_env/lib/python3.6/site-packages/glfw/__init__.py:834: GLFWError: (65543) b'GLX: An OpenGL profile requested but GLX_ARB_create_context_profile is unavailable'

**Comment by ErenBalatkan** [comment]
Greetings,

The error you are facing is coming from glfw package, can you forward the issue to them?
https://github.com/FlorianRhiem/pyGLFW
